travis:
  secure:
    BINSTAR_TOKEN: Hk4czGM4JHpC1mwALK4CyxvZVrPWUX7LL4yHmLfzrZ57P2+3TleMwSYohfCJIA4yPkc/Rl8hvSj5SL7BnbA8VClBqnESORSKcvNi+swW/XYZ6Q8ZemFneCZSqwIkH03GOUsaXgOceqf+QZq0+gDPxPl4PAsBn7Iuu80b53JrGdHoz27Xt2mEPF1F+OjT3fPX0e8ZNf+RtrvBuY9hZPKrXahxrex1vXz9z1qxUsgLcScrFc/mhDfx+zsYFH9hEalqlTxCCBNfvscn4yRNFRXqomC0zHHjc0p3TxuFoKzcpurKSWyNRqYnYpuYjIdzriPSlqhIGLYb4c6EzYMyz7v3gtQtvcy0Rj0Q7D/C4i0sB7wD4n4vb4YgG6n/veU9O2NeOGVAoPgkQiGqCsBcI+Hx0AY4ujbGuAHLm9tg5HCi6y6hTzJ4daJtT9ITrwxvTIJlsuuUG7HWqsPIc26f4QsO89/Ko1XoHPVW+nDD8VNt79eF/m/p7WVqEQ/kMtzNtulJA8smdMDRpIKcInF9yDBXf3DbdRlfaKEAXMcgVemNfxXhRNlfj89IXNAZtkcXBS63shB3gpEnMH7hbK29dGGhchBv4dux/z6I6djeP53NusMTSNnNEVnr9gpzUOk5WqbLhSb2ElicNHX4taXGC/194nfUtdJcvNolOZWLlfXRm+A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
