appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: myiVIoiTK9J5dyOXEzClEuFQe4NnrcYY6YPtFsBwh+pd1SugJ1MS4Z84lqIc3QaLTQGayiu1SJk+G+cpIsnpdhjLTfaASAd/P2SioHsmMex4e9doSyK4OYthNkpswR6MYK+eXjKYYVGnbQa4FxhoOB00Q59M/KMkd5dIUEXr8X2ex1Y98GBnjdoBgd0bLvE8hQsxyW4+D0+D2PhpnN9O772gqBN8Qtktfn56BQ0aX8PkNMOHs+R6q/q6UVqjIpaIEw4SXTiShNlaSpvtW4o31/k28fptnzETk3QHfEGCwuCsFRuhNpyxzmgzFYOILLp8n+KNEUDPwKGrJ1kQmG0uhTFUoJBlMBl4t+woGecaETLEiv/0ysLlGHTabYCGwQArbre7nQT9xXMB3PdooBvL+lWuP9TiaIKshxspMUW9RyRQmAcvqvBE1N4jr/H64iyqGDWR6iauRGsB9Eqhb0bS7lAwRXJ4e0lPXxt4mNeSSNMdYtGO2+bTipXM56B+MUbtQIzkzwJ72ikYzyAaPblXSJbqVNflmJ+lGcnFiBw0J8UOn+zMxUbQD+Pus/cW8SLpuXP7CYesNC2kNzvlY3rtPgokkZpkJ+/HShQhAg/jP92O3cShyIS3atJPfj5N6Ck7qzG+i2aYcj/7HX7KdFKyFVOL/F7NuhxpMAsfULvOasU=
conda_forge_output_validation: true
